fakeStore.api : "https://fakestoreapi.com/products"
#logging:
#  level:
#    root: INFO
#    com.example.ecommerce: INFO
logging.file.name : console.log
server:
  port : 9000
spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  security:
    user:
      name: dheeraj
      password: dheeraj123
#Secret key
secret.key: sdkfjaskldjfaksjdfkjdlkjfkjoiewurx,nmckljq;jsdskfl

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


#  devtools:
#    restart:
#      enabled: true          # enable/disable auto restart
#      additional-paths: src/main/java
#      exclude: static/**,public/**
#    livereload:
#      enabled: true
    #debug : true
      #  h2:
      #    console:
      #      enabled: true
      #  datasource:
      #    url: jdbc:h2:file:D:/Learning/preparation/h2Db
      #    driver-class-name: org.h2.Driver
      #    username: sa
      #    password:




